Update test

diff --git a/test b/test
--- a/test
+++ b/test
@@ -82,3 +82,76 @@ Notifications about newly disclosed issues related to these dependencies will be
 [Pipeline] sh
 + ls /var/lib/jenkins/workspace/snyk-email/*_snyk_report.json
 ls: cannot access '/var/lib/jenkins/workspace/snyk-email/*_snyk_report.json': No such file or directory
+
+
+pipeline {
+    agent any
+    tools { nodejs "npm" }
+    environment {
+        SNYK_API = "${env.SNYK_API}"  
+    }
+
+    stages {
+        stage('checkout') {
+            steps {
+                git branch: 'master', credentialsId: 'PAT', url: 'https://git.stldev.io:1305/pradeepkumar.n/angular-ng.git'
+            }
+        }
+        stage('Build') {
+            steps {
+                echo 'Building...'
+                sh "npm install"
+                sh "npm run build"
+            }
+        }
+        stage('Test') {
+            steps {
+                echo 'Testing...'
+                snykSecurity(
+                    snykInstallation: 'snyk@latest',
+                    snykTokenId: 'snyk-token',
+                    //place other parameters here
+                )
+
+                // Find the dynamically generated Snyk JSON report and convert it to HTML
+                script {
+                    def snykJsonFile = sh(
+                        script: "ls ${WORKSPACE}/*snyk_report*.json || echo 'NOT_FOUND'",
+                        returnStdout: true
+                    ).trim()
+                    
+                    if (snykJsonFile == 'NOT_FOUND') {
+                        error "Snyk JSON report not found!"
+                    } else {
+                        echo "Found Snyk report: ${snykJsonFile}"
+                        sh "/var/lib/jenkins/tools/io.snyk.jenkins.tools.SnykInstallation/snyk_latest/snyk-to-html-linux -i ${snykJsonFile} -o ${WORKSPACE}/snyk_report.html"
+                    }
+                }
+            }
+        }
+        stage('Deploy') {
+            steps {
+                echo 'Deploying...'
+                // Your deploy steps go here
+            }
+        }
+    }
+
+    post {
+        success {
+            // Archive the Snyk HTML report
+            archiveArtifacts artifacts: 'snyk_report.html', allowEmptyArchive: true
+            
+            // Send the email with the HTML report attached
+            emailext(
+                to: 'kanchanagm@stellaripl.com',
+                subject: "Jenkins Build: ${currentBuild.currentResult}: ${env.JOB_NAME}",
+                body: """${currentBuild.currentResult}: Job ${env.JOB_NAME}
+                More Info can be found here: ${env.BUILD_URL}""",
+                attachLog: true,
+                attachmentsPattern: 'snyk_report.html'
+            )
+        }
+    }
+}
+
